### ISSUE TITLE
Lovelace error with HA .106 with covers and locks 

### ISSUE THREAD

**Issue by gary-reyes** [iantrich/restriction-card#13]
I have configurations where I restrict covers and locks. These are not loading with HA  .106

**Comment by iantrich** [comment]
Fixed in 1.1.8

**Comment by gary-reyes** [comment]
I trie 1.1.8 but still see the same issue with lock and cover entities

**Comment by iantrich** [comment]
If you open your browser console, does it print out that you have 1.1.8 installed?

**Comment by gary-reyes** [comment]
HACS does. 
I am not sure what to look for or where exactly to look at in the console.

Also, one of the first things I did was uninstall and reinstall.

A bit more info:
I added a cover entity without restriction and a cover entity with restriction. This configuration shows both entities. If I only have the cover entity with restriction, nothing shows up, only a cropped red window. 

Similarly, If I have 1 lock entity without restriction and other entities without restrictions,  everything shows up. If I all locks have restrictions, none show up.
